base_url = "https://pakweight.com"
title = "THE PAKWEIGHT SHOW"
description = "This is The Pakweight Show."
build_search_index = true
generate_feeds = true
feed_filenames = ["podcast.xml"]
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]
theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = false
use_cdn = false
favicon = "/icon/favicon.png"
theme = "dark"              # light, dark, auto, toggle
comment = false
fancy_code = true
dynamic_note = true # a note that can be toggled
h_anchor_link = true
# mathjax = true
# mathjax_dollar_inline_enable = true

menu = [
    { name = "episodes", url = "/episodes", weight = 1 },
    { name = "about", url = "/about", weight = 2 },
    { name = "tags", url = "/tags", weight = 3 },
]

socials = [
    { name = "YouTube", url = "https://youtube.com/@pakweight", icon = "youtube" },
    { name = "Spotify", url = "https://open.spotify.com/show/70TGawrgg0wcbU1EHG13z4", icon = "spotify" },
    { name = "Apple", url = "https://podcasts.apple.com/us/podcast/the-pakweight-show/id1753893319", icon = "apple" },
    { name = "Fountain.fm", url = "https://fountain.fm/show/jVXm5uIE4TKNcYtRNZHZ", icon = "bitcoin" },
    { name = "Email", url = "mailto:info@pakweight.com", icon = "email" },
    # { name = "Twitter", url = "https://x.com/pakweight", icon = "twitter" },
    { name = "RSS", url = "/podcast.xml", icon = "rss" },
]

custom_css = []

[extra.analytics]
enabled = true

[extra.analytics.google]
id = "G-ZD6L5J3GDS"
